# Get location of Gpuengine library dir
GET_TARGET_PROPERTY(GPUENGINE_LOCATION geCore LOCATION)
GET_FILENAME_COMPONENT(GPUENGINE_LIBRARY_DIR ${GPUENGINE_LOCATION} DIRECTORY)
# Get location of Effects library dir
GET_TARGET_PROPERTY(EFFECTS_LOCATION Effects LOCATION)
GET_FILENAME_COMPONENT(EFFECTS_LIBRARY_DIR ${EFFECTS_LOCATION} DIRECTORY)

# Pack all library dirs to list
SET(LIBRARY_DIRS ${GPUENGINE_LIBRARY_DIR} ${ASSIMP_LIBRARY_DIRS} ${EFFECTS_LIBRARY_DIR})

INCLUDE(GNUInstallDirs)
INCLUDE(InstallRequiredSystemLibraries)
INCLUDE(DeployQt5)

#Install executable
INSTALL(TARGETS ${PROJECT_NAME} RUNTIME DESTINATION ".")
#Install shared objects (dynamic linked libraries)
INSTALL_QT5_EXECUTABLE("${PROJECT_NAME}" "" "" "${LIBRARY_DIRS}" "")

#Install run script for linux
INSTALL(CODE "file(WRITE ${CMAKE_INSTALL_PREFIX}/run.sh 
\"
LD_LIBRARY_PATH=.
export LD_LIBRARY_PATH
./DemoApp
\")")

#Install resources directory
INSTALL(DIRECTORY ${CMAKE_SOURCE_DIR}/resources DESTINATION ${CMAKE_INSTALL_PREFIX})